# config/config.yaml
gcp:
  project_id: 541368634993  # Corrected to match the output
  location: us-central1
  bucket_name: technical-test-datalabs
  source_blob_name: ASK DATA - superstore_data.csv
  bq_dataset: ask_data_dataset
  bq_table: superstore_data
  index_name: projects/541368634993/locations/us-central1/indexes/7049677131160223744  # Corrected project ID
  endpoint_name: projects/541368634993/locations/us-central1/indexEndpoints/267185723596079104  # Corrected project ID
  deployed_index_id: datalabs_test_1740982900021  # Updated to match deployed ID

llm:
  model_name: gemini-1.5-pro
  generation_config:
    temperature: 0.2
    max_output_tokens: 1024
    top_p: 0.8
    top_k: 40

embeddings:
  model_name: textembedding-gecko@003

retrieval:
  num_neighbors: 200

data_limit: 10000