[gcp]
project_id = "541368634993"
location = "us-central1"
bq_dataset = "ask_data_dataset"
bq_table = "superstore_data"
service_account_key = '''
{
  "type": "service_account",
  "project_id": "datalabs-test-452308",
  "private_key_id": "db013ff891d83f6c6674903e22c9d6711591838a",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRkLz/0ZJ1B1u7\nNmdH4cMrkQnQdt6hMH2Z7Fv4b+khovAHHs3P07PQ2LeYVXSfDrrd+Lo4CnDYNoCm\nCpa3QSH5s+G2oYOu/ZZAlf+E5Pe0xqb+4pyUJQShx2t68X3h0oyTVBTlohqleTLv\n2VqlibAgcr54UpZRiU0zk9MhfIRAE1viHgv663rlPAQDeA8lGWestZpMRt6DIjWs\nTOjDV+4EcJ4IKC3qrW3MGH1wSVL9Xop23tCs/iMn2bO1SzNn3JYEYIdPwVK9zuNo\nuQ9Q9Ez9Ud0+tVh+Zly0gkD98G96kTSAF86isGyynaf9OF7oFubLgFxYGrjrywN1\ncGUtucgBAgMBAAECggEABouty5PBLlSXgeZ2HWGo1fCGzPMZixFXqvod+UmNj5Zm\nRuKobQhgwnIycdihduJf5dUCBAQXeDljlUwZXwnyxLjgoPK0iT+0dLn6rCz2q7fU\nuXtchqgNV/xBmCp40xffei6TJIUGrgp2E9XHJgqB7NGIr3ts5IkUVzsTyiT4gIPL\nyUlNGFZPPUgsXw5gOBFRpB+MMTuAW6UrBGegVMPQyNww6a11RVkpCar+idFJ/mzO\nRne4gJBGZiz1TyuQgrfZ/ceaCFniA9oT4dwq5wShTfKJbtYMKP/eonUcb4FDvZ2x\na+z2/N0a8d/XolU0gLxwO4qOYku3oUYThBQemHp9LQKBgQD1vKdfBWEeV8yifTR+\nRnKnLa3aAIw6CZ4ft+etLRRmQmLWytPpbAatLxdx908bwacClBGfCxQbqxu04Q1F\nRJUAitpmob33LalAdUrtGt9ggXw+B+O/8EcbrRM4KbUf9nAFIHj1zO5yIacVtrGK\nOuCPjLjqmW+/cwp/ED8AFOdTuwKBgQDaUVldFyGdApDQzNR6LZ9o5e6TDRyd0/6Q\nEVRB6ole51M3L4ascddaVbcboQS+lckzr4bpz9bmSiw9F+pt6jTcbjG8IvSuAvEE\n4apRVgfgh9wz3XcNWzfv0tCYcnivU+1HrtxjTI3aLZD1TUzSrthsghaeCPEEmm4g\n08ritWNRcwKBgQDDMy+UqHZEHyRbcq+vGxDaQcvW3xaEx70GnxR2mNeaf2N6EbYR\ntpD7IuwxyGzbtJGQ18PDnY5EiEBDB35+JoNh4eqpGhQHdAr9O+7ft7f3NgRWVfgR\nMLGbh3k75M2O7TiAqhHL1xUWLitGcVBIaIqXHQaKvIVrA9wzoNkanIBBHwKBgFMU\nmhle8B+8Fjgfesx0CDH3Lm8vkjBNuJZCwfnDszs2dOiPYYTGXdm2vNP61r9gaQ0O\nQx0/RtykZWlqbIAfnLY2CR87fjmqTOY6qoIBZ0X+7cGfCes/R24wn8kj5uFx4t5g\noOX5ABKDPKLdI9sZRqskZk8FwBKsYjSD5LWZqY4ZAoGBANKYQTa01yUl90xTCxRr\nXb1iJPZApXDC2isdto/Qw62U4PcVaU30hKHb0WjPp0FCpsXvYMUl9tCsFHwTXLso\nc9/Y3HSiq27LjsWGf+Bo8ucgz8Ji4Ap7iIERv0BkTjI7Q4JDMF9M7pvcgfgI0XCP\nOiCZ+QIHlm2edcl2Rh4aYNAS\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-app-user@datalabs-test-452308.iam.gserviceaccount.com",
  "client_id": "113645156901682607549",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app-user%40datalabs-test-452308.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''

[llm]
model_name = "gemini-1.5-pro"
generation_config.temperature = 0.2
generation_config.max_output_tokens = 1024
generation_config.top_p = 0.8
generation_config.top_k = 40